version: "3"
services:
  postgresql:
    image: postgres:12.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=catch
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      - POSTGRES_HOST_AUTH_METHOD=trust
      - TZ="Asia/Tokyo"
    user: root
    volumes:
      - ./docker/postgresql/:/docker-entrypoint-initdb.d

  go:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src/:/go/src/catch
    tty: true
    depends_on:
      - postgresql
