// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Categories      string
	Categorizations string
	Clips           string
	Customers       string
	Locations       string
	Stores          string
	Users           string
	Visits          string
}{
	Categories:      "categories",
	Categorizations: "categorizations",
	Clips:           "clips",
	Customers:       "customers",
	Locations:       "locations",
	Stores:          "stores",
	Users:           "users",
	Visits:          "visits",
}
