name: catch
# host: localpride-database-2.c0wy7zi5zmc7.ap-northeast-1.rds.amazonaws.com
host: postgresql
port: 5432
# password: Higashi624
password: pass
# user: master_user
user: local_user
schema: catch
sslmode: disable
maxidleconns: 5
maxopenconns: 5
connmaxlifetime: 8h # string (use for time.ParseDuration())
databasedriver: postgres
