psql:
  dbname: catch
  host: postgresql
  port: 5432
  password: pass
  user: local_user
  sslmode: disable
  tags:
    json: "json"
  # whitelist:
  #   - categorization
  #   - category
  #   - clip
  #   - customer
  #   - location
  #   - store
  #   - user
  #   - visit
